import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import WalletBadge from "@/components/WalletBadge";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boss Auto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignInUrl="/dashboard" afterSignUpUrl="/dashboard">
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="siteHeader">
            <div className="headerInner">
              <div className="brand">Boss Auto</div>
              <div className="headerButtons">
                <SignedOut>
                  <SignInButton mode="modal">
                    <button className="btn btnSecondary">Sign In</button>
                  </SignInButton>
                  <SignUpButton mode="modal">
                    <button className="btn btnPrimary">Sign Up</button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <Link href="/dashboard" className="btn btnSecondary">Dashboard</Link>
                  <Link href="/dashboard/billing" className="walletBadge" data-testid="wallet-badge"><WalletBadge /></Link>
                  <UserButton appearance={{ elements: { userButtonBox: "userButtonBox" } }} />
                </SignedIn>
              </div>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
